ARG JITSI_REPO=jitsi
FROM ${JITSI_REPO}/base-java

COPY jicofo.deb /tmp/jicofo.deb

RUN \
       apt-dpkg-wrap apt-get update && \
       apt-dpkg-wrap apt-get install -y ruby-hocon && \
       apt-cleanup

COPY rootfs/ /

RUN \
	export DEBIAN_FRONTEND=noninteractive && \
	dpkg -i /tmp/jicofo.deb

VOLUME /config

